Repository Lim-Ji-Hyeon/ReactShop, pull requests merged in 2022-06, with the labels that each got.

#7 Feat: axios 모듈화 및 디렉토리 수정
  src/api/axios.js
  src/data/CarouselDummy.js
  src/views/Accessory.jsx
  src/views/Cart.jsx
  src/views/Digital.jsx
  src/views/Fashion.jsx
Labels: Feat

#8 Feat : 별점 컴포넌트 추가
  src/components/common/StarRating.jsx
Labels: Feat

#6 Feat : breadCrumbs 추가
  src/components/common/BreadCrumbs.jsx
Labels: Feat

#5 Feat : 뱃지 컴포넌트 추가
  src/components/common/Badge.jsx
Labels: Feat

#9 Revert "Feat : 별점 컴포넌트 추가"
  src/components/common/StarRating.jsx
Labels: Revert

#10 Refactor : 별점 컴포넌트 코드 수정
  src/components/common/StarRate.jsx
Labels: Revert

#4 Feat : 버튼 컴포넌트 추가
  src/App.jsx
  src/components/Button.jsx
  src/components/Footer.jsx
  src/components/common/Button.jsx
  src/components/common/header/Header.jsx
  src/components/common/header/HeaderCollection.jsx
  src/data/footerData.js
  src/data/theme.js
  src/views/Fashion.jsx
Labels: Feat

#11 Lina-refactor
  src/App.jsx
  src/components/Badge.jsx
  src/components/BreadCrumbs.jsx
  src/components/Button.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/StarRate.jsx
  src/components/card/CardItem.jsx
  src/components/card/CardList.jsx
  src/components/card/CardSection.jsx
  src/components/carousel/Carousel.jsx
  src/components/common/Badge.jsx
  src/components/common/BreadCrumbs.jsx
  src/components/common/Button.jsx
  src/components/common/header/HeaderCollection.jsx
  src/data.js
  src/data/theme.js
  src/index.css
  src/utils/theme.js
  src/views/Accessory.jsx
  src/views/Fashion.jsx
  src/views/MainPage.jsx
Labels: Refactor

#12 Chore : Redux toolkit 패키지 설치
  package-lock.json
  package.json
  yarn.lock
Labels: Chore

#13 Feat : CardItem, CardList 컴포넌트 구현
  src/api/axios.js
  src/components/card/CardItem.jsx
  src/components/card/CardList.jsx
  src/components/card/CardSection.jsx
  src/components/card/index.jsx
  src/img/temp.jpg
  src/views/MainPage.jsx
  yarn.lock
Labels: Feat

#14 Lina product page
  package-lock.json
  package.json
  src/App.jsx
  src/components/BreadCrumbs.jsx
  src/components/Button.jsx
  src/components/Header.jsx
  src/store/index.js
  src/utils/theme.js
  src/views/ProductPage.jsx
  yarn.lock
Labels: Feat, Refactor, Chore

#15 Lina category page
  src/views/Accessory.jsx
  src/views/Digital.jsx
  src/views/Fashion.jsx
Labels: Refactor

#16 Lina store
  package-lock.json
  package.json
  src/App.jsx
  src/components/Header.jsx
  src/redux/mode.js
  src/redux/product.js
  src/redux/store.js
  src/store/index.js
  yarn.lock
Labels: Feat, Refactor, Chore

#17 Refactor : 카드 링크 추가
  src/App.jsx
  src/components/card/CardItem.jsx
  src/components/card/CardList.jsx
  src/redux/product.js
  src/views/ProductPage.jsx
Labels: Refactor

#19 Feat : 카테고리 페이지 필터 기능 추가
  src/hook/Filter.jsx
  src/views/Accessory.jsx
  src/views/Digital.jsx
  src/views/Fashion.jsx
Labels: Feat

#20 Feat : 상품 데이터 캐싱 Redux 파일 추가
  src/redux/setProduct.js
  src/redux/store.js
  src/views/Accessory.jsx
  src/views/Digital.jsx
  src/views/Fashion.jsx
  src/views/MainPage.jsx
  src/views/ProductPage.jsx
Labels: Feat, Refactor

#22 Refactor : publicDir 설정
  src/views/MainPage.jsx
  vite.config.js
  yarn.lock
Labels: Chore

#24 Refactor : Redux 에러 발생 코드 수정
  src/App.jsx
  src/components/Header.jsx
  src/views/Accessory.jsx
  src/views/Digital.jsx
  src/views/Fashion.jsx
  src/views/MainPage.jsx
Labels: Refactor

#25 Feat : Cart 페이지, CartModal 컴포넌트 추가
  src/components/Button.jsx
  src/components/CartModal.jsx
  src/components/carousel/Carousel.jsx
  src/redux/cart.js
  src/utils/theme.js
  src/views/Cart.jsx
  src/views/MainPage.jsx
  vite.config.js
Labels: Feat

#23 Lina search
  src/components/Header.jsx
  src/components/Search.jsx
  src/views/ProductPage.jsx
Labels: bug, Feat, Refactor
